[package]
name = "rust_bee"
version = "0.1.0"
authors = ["ilgaleanos <ilgaleanos@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
plotters = "0.3.0"